name = "kataleya-server"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

[[d1_databases]]
binding = "DB"
database_name = "kataleya"
database_id = "87e1374c-11d6-4cbf-a81a-422497d01ac3"

[[r2_buckets]]
binding = "IMAGES"
bucket_name = "kataleya-images"

[[durable_objects.bindings]]
name = "SYNC_ROOM"
class_name = "SyncRoom"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["SyncRoom"]

[vars]
JWT_ISSUER = "kataleya"

# Secrets (à créer via: wrangler secret put JWT_SECRET)
# JWT_SECRET
